repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
            args: [--allow-multiple-documents]
            exclude: ^deploy/charts/.*/templates/.*
        -   id: check-added-large-files
  -   repo: https://github.com/golangci/golangci-lint
      rev: v2.8.0
      hooks:
        -   id: golangci-lint
  -   repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.23
      hooks:
        -   id: helmlint
