apiVersion: v2
name: metric-cacher-exporter-helm
description: A Helm chart for metric-cacher-exporter
type: application
version: 0.0.6
appVersion: "0.0.6"
dependencies:
  - name: redis
    version: ">=18.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled